pipeline {
  environment {
   PROJECT = "shaped-glazing-379621"
	//PROJECT = "shaped-glazing-3796218"
    APP_NAME = "binary-calculator2"
	//CLUSTER = "gke_shaped-glazing-379621_northamerica-northeast1-b_sofe3980u"
    CLUSTER = "sofe3980u"
    CLUSTER_ZONE = "northamerica-northeast1-b"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}"
    JENKINS_CRED = "shaped-glazing-379621"
  }
  
agent {
    kubernetes {
	label 'sample-app'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: cd-jenkins
  containers:
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    //image: google/cloud-sdk:latest
    command:
    - cat
    tty: true
  - name: kubectl
    image: gcr.io/cloud-builders/kubectl
    command:
    - cat
    tty: true
"""
}
  }
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
	    checkout scm
        sh 'echo "Start of Job"'
      }
    }
    //stage ('test') {
    //  steps {
    //    sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
    //  }
    //}
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
stage('Build and push image with Container Builder') {
      steps {
        container('gcloud') {
sh "/builder/google-cloud-sdk/bin/gcloud auth activate-service-account shaped-glazing-379621@shaped-glazing-379621.iam.gserviceaccount.com
 --key-file= ./shaped-glazing-379621-4f9031974484.json
--project=shaped-glazing-379621"
sh "/builder/google-cloud-sdk/bin/gcloud builds submit -t ${IMAGE_TAG} ./BinaryCalculatorWebapp/"
}

    }
  }
}
} 
