pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        // build your application and create a container image
        sh 'docker build -t my-image .'
        // push the container image to a registry
        sh 'docker push gcr.io/my-project/my-image'
      }
    }
    stage('Deploy') {
      environment {
        // set the GKE cluster and namespace
        GKE_CLUSTER = 'my-cluster'
        GKE_NAMESPACE = 'my-namespace'
      }
      steps {
        // deploy the application to GKE
        sh "gcloud container clusters get-credentials ${GKE_CLUSTER}"
        sh "kubectl config set-context --current --namespace=${GKE_NAMESPACE}"
        sh "kubectl apply -f kubernetes/deployment.yaml"
        sh "kubectl apply -f kubernetes/service.yaml"
      }
    }
  }
}
